spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: sandeep
    url: jdbc:mysql://localhost:3306/jrtp12
    username: root		
  jpa:
     hibernate:
       ddl-auto: u
     show-sql: true

server:
   port: 4200
	 

	mail:
	  host: smtp.gmail.com
	     port: 587
	     username: sdeepmail419@gmail.com
	     password: your-email-password
	     properties:
	       mail:
	         smtp:
	           auth: true
	           starttls:
	             enable: true
